TheaterCinemaApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shows/', include('shows.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.home, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path("signup/", views.signup_view, name="signup"),
  path("login/", views.login_view, name="login"),
  path("logout/", views.logout_view, name = "logout"),
]

shows/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


app_name = 'shows'

urlpatterns = [
   path('checkMovie/seatDetails/<slug:slug>/<int:seatCode>', views.reserveASeat, name ="reserveASeat"),
   path('checkMovie/<slug:slug>/', views.checkMovieDetails, name ="checkMovieDetails"),
   path('editMovie/<slug:slug>/', views.editMovieDetails, name ="editMovieDetails"),
   path('editMovieList/', views.editMovieList, name="editMovie"),
   path('addNewMovie', views.addNewMovie, name="addNewMovie"),
   path('yourReservations', views.yourReservations, name="yourReservations"),
   path('errorPage', views.errorPage, name="errorPage"),
   path('', views.show_list, name="list"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TheaterCinemaApp/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
  # return HttpResponse('homepage')
  return render(request, "homepage.html")


def about(request):
  # return HttpResponse('about')
  return render(request,"about.html")

TheaterCinemaApp/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    <title>Not Blockbuster</title>
  </head>
  <body>
    <nav id="navbar">
      <a href="{% url 'shows:list' %}"><img src="{% static 'logo.png' %}" id="logoImage" class ="navbarElement"/></a>
      <a href="{% url 'shows:list' %}" class ="navbarElement">Browse Movies</a>
      {% if user.is_authenticated %}
      Logged in as {{user}}
      <form
        action="{% url 'accounts:logout' %}"
        class="logout-link"
        method="post"
        style="display:inline"
      >
        {% csrf_token %}
        <button type="submit" class="nav-links">Logout</button>
      </form>
      <a href="{% url 'shows:yourReservations' %}" class ="navbarElement">Your Reservations</a>
      {% else %}
      <a href="{% url 'accounts:signup' %}" class ="navbarElement">Sign up</a>
      <a href="{% url 'accounts:login' %}" class ="navbarElement">Log In</a>
      {% endif %}
      
    </nav>

    {% block content %} {% endblock %}
  </body>
</html>

TheaterCinemaApp/templates/homepage.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Homepage Goes Here</h1>


{% endblock %}