TheaterCinemaApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shows/', include('shows.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.home, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shows/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


app_name = 'shows'

urlpatterns = [
   path('checkMovie/seatDetails/<slug:slug>/<int:seatCode>', views.reserveASeat, name ="reserveASeat"),
   path('checkMovie/<slug:slug>/', views.checkMovieDetails, name ="checkMovieDetails"),
   path('editMovie/<slug:slug>/', views.editMovieDetails, name ="editMovieDetails"),
   path('editMovieList/', views.editMovieList, name="editMovie"),
   path('addNewMovie', views.addNewMovie, name="addNewMovie"),
   path('yourReservations', views.yourReservations, name="yourReservations"),
   path('errorPage', views.errorPage, name="errorPage"),
   path('', views.show_list, name="list"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shows/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

screeningRoomChoices = (
  ('1', '1'),
  ('2', '2')
)

class newShow(models.Model):

  class screeningRoomChoices(models.IntegerChoices):
        Room1 = 1
        Room2 = 2

  title = models.CharField(max_length=100,default="untitled")
  slug = models.SlugField(default="")
  startTime= models.DateTimeField(default="1970-01-01 00:00:00")
  endTime = models.DateTimeField(default="1970-01-01 00:00:00")
  cancelTime = models.DateTimeField(default="1970-01-01 00:00:00")
  description = models.TextField(default="To Be Filled")
  posterImage = models.ImageField(default='default.png')
  screeningRoom = models.IntegerField(choices=screeningRoomChoices.choices, default='0')

  def __str__(self):
    return self.title


class reservation(models.Model):

  now = datetime.datetime.now()

  title = models.CharField(max_length=100,default="untitled")
  seatNumber = models.IntegerField(default = 0)
  reservee = models.CharField(max_length=100,default="untitled")
  startTime = models.DateTimeField(default="1970-01-01 00:00:00")
  cancelTime = models.DateTimeField(default="1970-01-01 00:00:00")

  def __str__(self):
    reservationName = self.title + ": Seat " + str(self.seatNumber)
    return reservationName

shows/forms.py
from django import forms
from . import models

class addNewShow(forms.ModelForm):

  class Meta:
    model = models.newShow
    fields = ['title', 'description', 'startTime', 'endTime', 'posterImage', 'screeningRoom']

shows/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import newShow
from django.contrib.auth.decorators import login_required
from . import forms
from django.shortcuts import get_object_or_404
import re
from .models import reservation
from string import Template


# Create your views here.

def show_list(request):
  shows = newShow.objects.all().order_by('startTime',)
  return render(request, 'availableShows.html', {'shows':shows})


def addNewMovie(request):
  print(request)
  if request.method == 'POST':
    form = forms.addNewShow(request.POST, request.FILES)
    if form.is_valid():
      instance = form.save(commit=False)
      instance.slug = instance.title.lower().replace(" ", "-")
      
      instance.save()
      return redirect('shows:list')
    else:
      return render(request, 'addNewMovie.html')

  else:
    form = forms.addNewShow()
    # field = form.fields['slug']
    # field.widget = field.hidden_widget()
  return render(request, 'addNewMovie.html', {'form':form})


def editMovieList(request):
  shows = newShow.objects.all().order_by('date',)
  return render(request, 'editMovieList.html', {'shows':shows})


def editMovieDetails(request,slug):
  if request.method == 'POST':
    form = forms.addNewShow(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return redirect('shows:list')
  else:
    movie = newShow.objects.get(slug=slug)
    form = forms.addNewShow(instance=movie)
    return render(request, 'editMovieDetails.html', {'movie':movie,'form':form})


def checkMovieDetails(request,slug):
  movie = newShow.objects.get(slug=slug)
  reservations = reservation.objects.filter(title=slug)

  x=1
  if movie.screeningRoom==1:
    totalSeats = x*20
  else:
    totalSeats = x*30

  seatList = enumerate(["0"] * totalSeats, start=1)
  seatDiagram = []

  print(seatDiagram)

  for i in seatList:
    occupiedSeat=False
    print("checking seat")
    print(i[0])
    for j in reservations:
      if j.seatNumber == i[0]:
        print(":occupied")
        occupiedSeat=True
    if occupiedSeat==True:
      seatDiagram.append("Full Seat")
    else:
      seatDiagram.append("Empty Seat")

  print (seatDiagram)

  return render(request, 'checkMovieDetailscopy.html', {'seatDiagram':seatDiagram, 'movie':movie, 'totalSeats':range(totalSeats)})

def reserveASeat(request, seatCode, slug):
  if request.method == 'POST':
    username = request.user
    movie = newShow.objects.get(slug=slug)
    movieStartTime=movie.startTime
    movieTitle=movie.title
    print(seatCode, slug)

    rejectedapplication = 0
    reservations = reservation.objects.filter(title=slug)

    for j in reservations: 
      print("Checking a reservation with seat number ")
      print(j.seatNumber)
      if j.seatNumber == seatCode:
        rejectedapplication = 1

    if rejectedapplication == 0:
      reservation.objects.create(seatNumber=seatCode, title=movieTitle,reservee=username,startTime=movieStartTime)
    else:
      return render(request, 'errorPage.html', {})

    return redirect('shows:yourReservations')
  else:
    movie = newShow.objects.get(slug=slug)
    return render(request, 'seatDetails.html', {'seatCode': seatCode, 'movie':movie})

def yourReservations(request):
  username = request.user
  reservations = reservation.objects.filter(reservee=username)
  return render(request, 'yourReservations.html', {'reservations': reservations})

def errorPage(request):
  return render(request, 'errorPage.html', {})




# Screening Room 1 is 20 seats
# Screening Room 2 is 30 seats

# Add a credit card page for reserving a seat and check if the seat is already occupied at checkout - Done for adding of a new reservation, not added for credit or for verify occupied
# Add a list of the user's current reservations - DONE
# Add a button to cancel a reservation IF the time until the movie starts is more than 3 hours
# Fix editing features
# Search movies

shows/templates/addNewMovie.html
{% extends 'base_layout.html' %} {% block content %}

{% if user.managerValidated %}

<div class="addNewMovie">
  <h2>Add a new Movie.</h2>
  <form class="site-form" action="{% url 'shows:addNewMovie' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create">
  </form>
<div>
<!-- <script src="/assets/slugify.js"></script>  -->

{% else %}

<div> 404 </div>

{% endif %}

{%endblock%}

shows/templates/availableShows.html
{% extends 'base_layout.html' %} {% block content %}
<h1>Movie List</h1>

<div id="movieChangingButtons">
  {% if user.is_authenticated and user.userRole == manager and user.managerValidated == True %}
  <a href="{% url 'shows:addNewMovie' %}">Schedule a new Movie</a>
  <a href="{% url 'shows:editMovie' %}">Edit an existing Movie</a>
  {% endif %}
</div>

<div class="availableShowList">
  {% for newShow in shows %}
  <div class="showBlock">
    
    <img src="{{newShow.posterImage.url}}" class="posterImage" />
    <div style="margin-left: 10px;">
    <h2>{{newShow.title}}</h2>
    <p>{{newShow.description}}</p>
    <a href="{% url 'shows:checkMovieDetails' slug=newShow.slug %}"
      >Check this movie.</a
    >
    <div>{{newShow.startTime}}-{{newShow.endTime}}</div>
  </div>
  </div>
  
  {% endfor %}
</div>
{% endblock %}

shows/templates/checkMovieDetails copy.html
{% extends 'base_layout.html' %} {% block content %} {% load static %}

<div class="movieDetails">
  <div class="movie">
    <img src="{{movie.posterImage.url}}" style="width: 200px;height: 200px"/>
    <h2>{{movie.title}}</h2>


    <h2>Seat Availability: {{movie.remainingSeats}}/{% if movie.screeningRoom == 1 %} 20 {% else %} 30 {% endif%}</h2>


    <div id="seatsDiagram">
      {% for i in totalSeats %} 
        {% if forloop.counter <= movie.remainingSeats %}
          <img src="{% static 'unreservedSeat.png' %}" class="seatIndicator"><a href="{% url 'shows:checkSeatDetails' seatCode=forloop.counter %}"
          >Check this seat.</a
        ></img>
        {% else %}
          <img src="{% static 'reservedSeat.png' %}" class="seatIndicator">a href="{% url 'shows:checkSeatDetails' seatCode=forloop.counter %}"
          >Check this seat.</a
        ></img>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>

{%endblock%}

shows/templates/checkMovieDetails.html
{% extends 'base_layout.html' %} {% block content %} {% load static %}

<div class="movieDetails">
  <div class="movie">
    <img src="{{movie.posterImage.url}}" style="width: 200px;height: 200px"/>
    <h2>{{movie.title}}</h2>


    <h2>Seat Availability: {{movie.remainingSeats}}/{% if movie.screeningRoom == 1 %} 20 {% else %} 30 {% endif%}</h2>


    <div id="seatsDiagram">
      {% for i in totalSeats %} 
        {% if forloop.counter <= movie.remainingSeats %}
          <img src="{% static 'unreservedSeat.png' %}" class="seatIndicator"><a href="{% url 'shows:checkSeatDetails' seatCode=forloop.counter %}"
          >Check this seat.</a
        ></img>
        {% else %}
          <img src="{% static 'reservedSeat.png' %}" class="seatIndicator">a href="{% url 'shows:checkSeatDetails' seatCode=forloop.counter %}"
          >Check this seat.</a
        ></img>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>

{%endblock%}

shows/templates/checkMovieDetailscopy.html
{% extends 'base_layout.html' %} {% block content %} {% load static %}

<div class="movieDetails">
  <div class="movie">
    <img src="{{movie.posterImage.url}}" style="width: 200px;height: 200px"/>
    <h2>{{movie.title}}</h2>

    <div id="seatsDiagram">
      {% for i in seatDiagram %}
        {% if i == "Empty Seat" %}
            <a href="{% url 'shows:reserveASeat' seatCode=forloop.counter slug=movie.slug %}"> <img src="{% static 'unreservedSeat.png' %}" class="seatIndicator"></img> </a>
        {% else %}
            <img src="{% static 'reservedSeat.png' %}" class="seatIndicator"></img>
        {% endif %}
      {% endfor %}


    </div>
  </div>
</div>

{%endblock%}

shows/templates/editMovieDetails.html
{% extends 'base_layout.html' %} {% block content %}

{% if user.managerValidated %}


<div class="addNewMovie">
  <h1>You are editing {{movie.title}}</h1>
  <p>Details:
    ID: {{movie.id}}
    Name: {{movie.title}}
    Date: {{movie.date}}
    Poster Image: <a href="{{movie.posterImage.url}}">Click Here</a>
    Start Time: {{movie.startTime}}
    End Time: {{movie.endTime}}
    Screening Room: {{movie.screeningRoom}}
  </p>
  <form class="site-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Change">
  </form>
<div>


{% else %}

<div> 404 </div>

{% endif %}

{%endblock%}

shows/templates/editMovieList.html
{% extends 'base_layout.html' %}


{% block content %}
<h1>Which movie would you like to edit?</h1>
<div class="availableShowList">
  {% for newShow in shows %}
  <div class="showBlock">
    <img src={{newShow.posterImage.url}} class="posterImage">
    <h2>{{newShow.title}}</h2>
    <a href="{% url 'shows:editMovieDetails' slug=newShow.slug %}">Edit Movie</a>
  </div>
  {% endfor %}
</div>
{% endblock %}

shows/templates/errorPage.html
{% extends 'base_layout.html' %} {% block content %} {% load static %}

<h2> An error has occured. This seat might already be taken. </h2>

{%endblock%}

shows/templates/seatDetails.html
{% extends 'base_layout.html' %} {% block content %} {% load static %}

<div class="movieDetails">
  You are checking seat number {{seatCode}} for {{movie.title}}



  Click here to reserve this seat:
<form
    class="site-form"
    action="{% url 'shows:reserveASeat' seatCode=seatCode slug=movie.slug %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {{form}}
    <input type="submit" value="Click" />
  </form>
  
</div>

{%endblock%}

shows/templates/yourReservations.html
{% extends 'base_layout.html' %} {% block content %} {% load static %}

<div class="yourReservations">

  {% for reservation in reservations %}
  <div> You reserved Seat Number {{reservation.seatNumber}} in {{reservation.title}} for {{reservation.startTime}}
    You can cancel this reservation until 3 hours until the movie starts.
    
    Click here to cancel.

  </div>
  {% endfor %}
  
</div>

{%endblock%}